---
- name: change Azure VM status
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group_name: "oxxo"
    vm_name_list: ["RHEL-ansible"]
    # Set to present to create a VM with the configuration specified by other options, or to update the configuration of an existing VM.
    # Set to absent to remove a VM.
    # Does not affect power state. Use started/allocated/restarted parameters to change the power state of a VM.
  tasks:
     - name: Dump public IP for VM which will be created
      ansible.builtin.debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"
      when: survey_public_ip == "True"
        
