---
- name: Register VM_IP Artifact
  hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:
  - name: Save host data within a Group
    add_host:
      hostname: "{{ vm_ip }}"
      groupname: hardening_servers

  - name: Wait for SSH to come up
    wait_for: host={{ vm_ip }} port=22 delay=10 timeout=60
    
- name: Hardening Passwords
  hosts: hardening_servers
  become: true
  tasks:
    - name: Asegurar que firewalld est치 instalado y activo
      ansible.builtin.yum:
        name: firewalld
        state: present
      notify: 
        - Restart firewalld

    - name: Asegurar que firewalld est치 en ejecuci칩n
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Abrir el puerto 80/tcp en el firewall
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled

    - name: Recargar la configuraci칩n de firewalld
      ansible.posix.firewalld:
        immediate: yes
        state: reloaded

  handlers:
    - name: Restart firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted
      
